-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND
-- REGION TABLE
select COUNTRY_NAME,REGION_NAME from
COUNTRIES C JOIN REGIONS R on C.REGION_ID = R.REGION_ID;

-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
SELECT FIRST_NAME, JOB_TITLE FROM
                                 EMPLOYEES JOIN JOBS J on EMPLOYEES.JOB_ID = J.JOB_ID;
-- 3. FIND OUT DEPARTMENT_NAME AND CITY
SELECT DEPARTMENT_NAME, CITY FROM
                                 DEPARTMENTS D JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID;
-- 4. FIND OUT ALL CITIES AND COUNTRY NAMES
SELECT CITY, COUNTRY_NAME FROM
                              LOCATIONS C  JOIN COUNTRIES C2 on C.COUNTRY_ID = C2.COUNTRY_ID;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME
-- FOR DEPARTMENT ID 80 OR 40
SELECT FIRST_NAME,LAST_NAME,D.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID =40 OR D.DEPARTMENT_ID=80;

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
SELECT CITY, COUNTRY_NAME, REGION_NAME
FROM COUNTRIES C JOIN REGIONS R on C.REGION_ID = R.REGION_ID
JOIN LOCATIONS L on C.COUNTRY_ID = L.COUNTRY_ID
;

-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
SELECT FIRST_NAME,JOB_TITLE,DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY ,
-- COUNTRY_NAME , REGION_NAME
SELECT FIRST_NAME,JOB_TITLE,DEPARTMENT_NAME,CITY,COUNTRY_NAME,REGION_NAME
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN REGIONS R on C.REGION_ID = R.REGION_ID;

-- 9. FIND OUT EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL
-- DEPARTMENTS INCLUDING WHERE DO NOT HAVE ANY EMPLOYEE.
SELECT FIRST_NAME, LAST_NAME, D.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 10. FIND OUT ALL DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS WITH NO DEPARTMENT
SELECT DEPARTMENT_NAME,L.LOCATION_ID,COUNTRY_ID
FROM DEPARTMENTS D FULL JOIN LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID;

-- 11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT_NAME
SELECT DEPARTMENT_NAME,L.LOCATION_ID,COUNTRY_NAME
FROM DEPARTMENTS D JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
RIGHT JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

-- 12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT
-- NAME INCLUDING THOSE DOES NOT HAVE DEPARTMENT, INCLUDING THOSE
-- DEPARTMENTS DOES NOT HAVE ANY MATCHING EMPLOYEES
SELECT FIRST_NAME, D.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID;
