select * from employees;

-- who is Neena's M?
select  EMPLOYEE_ID, FIRST_NAME,LAST_NAME,MANAGER_ID
from EMPLOYEES;

select WORKERS.EMPLOYEE_ID,WORKERS.FIRST_NAME,WORKERS.LAST_NAME, WORKERS.MANAGER_ID,
       M.EMPLOYEE_ID,M.FIRST_NAME,M.LAST_NAME
from EMPLOYEES WORKERS JOIN EMPLOYEES M
ON WORKERS.MANAGER_ID = M.EMPLOYEE_ID;

--HOW I SEE ALL EMPLOYEES, EVEN THE ONE WHO DON'T HAVE MANAGER
select WORKERS.EMPLOYEE_ID,WORKERS.FIRST_NAME,WORKERS.LAST_NAME, WORKERS.MANAGER_ID,
       M.EMPLOYEE_ID,M.FIRST_NAME,M.LAST_NAME
from EMPLOYEES WORKERS LEFT JOIN  EMPLOYEES M
                            ON WORKERS.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY 1 ASC;

select W.EMPLOYEE_ID,W.FIRST_NAME,W.LAST_NAME, W.MANAGER_ID,
       M.EMPLOYEE_ID,M.FIRST_NAME,M.LAST_NAME
from EMPLOYEES W LEFT JOIN  EMPLOYEES M
                                  ON W.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY 1 ASC;