select * from customer;

select * from ADDRESS;

select  FIRST_NAME, LAST_NAME, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--What if I want to see customer table address_id information too.

select  FIRST_NAME, LAST_NAME,CUSTOMER.ADDRESS_ID,ADDRESS.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--TABLE ALIASES
-- CUSTOMER --C
-- EMPLOYEES --E
--ADDRESS --A

select  FIRST_NAME, LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C INNER join ADDRESS A
on C.ADDRESS_ID = A.ADDRESS_ID;


/* LEFT OUTER JOIN / LEFT JOIN
   --IT WILL GIVE MATCHING PART BETWEEN TWO TABLES + UNIQUE FOR FOR LEFT TABLE
   -- THE ORDER OF THE TABLE IS IMPORTANT*/

select  FIRST_NAME, LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C LEFT OUTER  join ADDRESS A
                           on C.ADDRESS_ID = A.ADDRESS_ID;

/* RIGHT OUTER JOIN / RIGHT JOIN
   --IT WILL GIVE MATCHING PART BETWEEN TWO TABLES + UNIQUE FOR FOR RIGHT TABLE
   -- THE ORDER OF THE TABLE IS IMPORTANT*/

select  FIRST_NAME, LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C RIGHT OUTER  join ADDRESS A
                                 on C.ADDRESS_ID = A.ADDRESS_ID;

/*FULL OUTER JOIN*/
select  FIRST_NAME, LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C FULL OUTER  join ADDRESS A
on C.ADDRESS_ID = A.ADDRESS_ID;