select *
from employees;

--Display all first name and related department_name
select FIRST_NAME,E.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES E join DEPARTMENTS D
on E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--ORDER THE LIST BASED ON FIRST_NAME ASC
select FIRST_NAME,E.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES E join DEPARTMENTS D
                      on E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME ASC ;

--ORDER THE LIST BASED ON FIRST_NAME ASC , DISPLAY ALL THE EMPLOYEES NAMES
select FIRST_NAME,E.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES E LEFT join DEPARTMENTS D
                      on E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY FIRST_NAME ASC ;



-- DISPLAY ALL FIRST NAME AND DEPARTMENT_NAME INCLUDING THE DEPARTMENT WITHOUT EMPLOYEE
select FIRST_NAME, DEPARTMENT_NAME
from EMPLOYEES E RIGHT join DEPARTMENTS D
                            on E.DEPARTMENT_ID=D.DEPARTMENT_ID ;

--HOW MANY EMPLOYEES WE HAVA IN EACH DEPARTMENT
select DEPARTMENT_NAME, COUNT(*)
from EMPLOYEES E RIGHT join DEPARTMENTS D on E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

--DISPLAY ALL FIRST NAME AND DEPARTMENT NAME INCLUDING THE DEPARTMENT WITHOUT EMPLOYEES
-- AND ALSO EMPLOYEES WITHOUT THE DEPARTMENT
SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--DISPLAY ALL CITIES AND RELATED COUNTRY NAMES
SELECT CITY,COUNTRY_NAME
FROM LOCATIONS L JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID;

--DISPLAY ALL CITIES AND RELATED COUNTRY NAMES INCLUDING WITH COUNTIES WITHOUT CITY.
SELECT CITY,COUNTRY_NAME
FROM LOCATIONS L RIGHT JOIN COUNTRIES C
                      ON L.COUNTRY_ID = C.COUNTRY_ID;

--DISPLAY ALL DEPARTMENTS NAME AND RELATED STREET ADDRESS
SELECT DEPARTMENT_NAME, STREET_ADDRESS
FROM DEPARTMENTS D JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

--DISPLAY FIRST NAME , LAST NAME, DEPARTMENT NAME , CITY FOR ALL EMPLOYEES

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID= D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID;

--DISPLAY FIRST NAME , LAST NAME, DEPARTMENT NAME , CITY, COUNTRY NAME FOR ALL EMPLOYEES
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME,CITY,COUNTRY_NAME, REGION_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID= D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
JOIN REGIONS R ON C.REGION_ID = R.REGION_ID;

--HOW MANY EMPLOYEES WORKING FOE EACH COUNTRY_NAME
SELECT COUNTRY_NAME, COUNT(*)
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L ON L.LOCATION_ID= D.LOCATION_ID
JOIN COUNTRIES C ON C.COUNTRY_ID=L.COUNTRY_ID
GROUP BY COUNTRY_NAME;

SELECT COUNTRY_NAME, COUNT(*)
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
                 JOIN LOCATIONS L ON L.LOCATION_ID= D.LOCATION_ID
                 JOIN COUNTRIES C ON C.COUNTRY_ID=L.COUNTRY_ID
GROUP BY COUNTRY_NAME
HAVING COUNT(*)>10;

--LEFT JOIN WITH WHERE

SELECT *
FROM CUSTOMER C LEFT JOIN ADDRESS A ON C.ADDRESS_ID=A.ADDRESS_ID
WHERE C.ADDRESS_ID IS NULL ;

SELECT *
FROM CUSTOMER C FULL JOIN ADDRESS A ON C.ADDRESS_ID=A.ADDRESS_ID
WHERE C.ADDRESS_ID IS NULL OR A.ADDRESS_ID IS NULL ;

